# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: kconf
before:
  hooks:
    - go mod download
builds:
  - binary: kconf
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/particledecay/kconf/build.Version={{ .Version }} -X github.com/particledecay/kconf/build.Commit={{ .ShortCommit }} -X github.com/particledecay/kconf/build.Date={{ .Date }}
archives:
- name_template: >-
    {{- .ProjectName }}-
    {{- tolower .Os }}-
    {{- if eq .Arch "amd64" }}x86_64
    {{- else }}{{ .Arch }}{{ end }}-
    {{- .Version }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: desc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
