---
name: release

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Create GitHub release
        uses: docker://goreleaser/goreleaser:latest
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
          GO111MODULE: on
          GOROOT: ""

      - name: Create Homebrew release
        uses: Justintime50/homebrew-releaser@v1
        with:
          homebrew_owner: particledecay
          homebrew_tap: homebrew-formulas
          formula_folder: formula
          github_token: ${{ secrets.github_token }}
          commit_owner: particledecay
          commit_email: ${{ secrets.committer_email }}

